; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[libs]
bno055 = adafruit/Adafruit BNO055
tinyusb = adafruit/Adafruit TinyUSB Library
adasensor = adafruit/Adafruit Unified Sensor, adafruit/Adafruit BusIO

[env]
platform = nordicnrf52
board = adafruit_feather_nrf52840
upload_protocol = nrfutil
framework = arduino
lib_archive = no

[knee_node]
lib_deps = ${libs.tinyusb}, ${libs.adasensor}, Wire, SPI, ${libs.bno055}
build_src_filter = +<configurations/knee_node.cpp> +<drivers/*>
build_unflags = -std=gnu++11
build_flags =  -I src/drivers/ -I src/ -std=gnu++17 -DBLE_NODE

[env:left_knee]
extends = knee_node
build_flags = ${knee_node.build_flags} -DBLE_ID=1


[env:right_knee]
extends = knee_node
build_flags = ${knee_node.build_flags} -DBLE_ID=2


[ankle_node]
lib_deps = ${libs.tinyusb}, ${libs.adasensor}, Wire, SPI, ${libs.bno055}
build_src_filter = +<configurations/ankle_node.cpp> +<drivers/*>
build_unflags = -std=gnu++11
build_flags =  -I src/drivers/ -I src/ -std=gnu++17 -DBLE_NODE

[env:left_ankle]
extends = ankle_node
build_flags = ${ankle_node.build_flags} -DBLE_ID=3

[env:right_ankle]
extends = ankle_node
build_flags = ${ankle_node.build_flags} -DBLE_ID=4

[env:hub]
lib_deps = ${libs.tinyusb}, ${libs.adasensor}, Wire, SPI, ${libs.bno055}
build_src_filter = +<configurations/hub.cpp> +<drivers/*>
build_unflags = -std=gnu++11
build_flags =  -I src/drivers/ -I src/  -std=gnu++17 -DBLE_HUB
